#!/bin/sh

export LD_PRELOAD=/home/mitchell/Documents/projects/foldingathome/yield_hook.so
#export YIELD_MODULUS=2
exec numactl --localalloc /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
#exec numactl --physcpubind=5-6,17-18,7-11,19-23 --membind=1 
#exec numactl --membind=1 /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
#exec numactl --interleave=0-1 /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
#exec numactl --membind=1 --cpunodebind=1 /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
#exec /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
