#!/bin/sh

#exec numactl --physcpubind=5-6,17-18,7-11,19-23 --membind=1 
#exec numactl --membind=1 /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
exec numactl --interleave=0-1 /var/lib/fahclient/cores/cores.foldingathome.org/v7/lin/64bit/avx/Core_a7.fah/FahCore_a7.orig $*
